### PR TITLE
Don't run sqlite code

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by csgillespie** [comment]
@Robinlovelace  What was wrong with the sqlite code? Is it a travis thing?

**Comment by Robinlovelace** [comment]
Not sure but I added it to close this: https://github.com/csgillespie/efficientR/issues/199

**Comment by csgillespie** [comment]
Does the sqlite code work on your machine?

**Comment by Robinlovelace** [comment]
Yep, try it:

```r
data(land_df, package="efficient")
my_db = src_sqlite("land.sqlite3", create = TRUE)
land_sqlite = copy_to(my_db, land_df, indexes = list("postcode", "price"))
tbl(my_db, sql('SELECT "price", "postcode", "old/new"  FROM land_df'))
select(land_sqlite, price, postcode, `old/new`)
```

```
Source:   query [?? x 3]
Database: sqlite 3.8.6 [land.sqlite3]

    price postcode `old/new`
    <int>    <chr>     <chr>
1   84000  CW9 5EU         N
2  123500 TR13 8JH         N
3  217950 PL33 9DL         N
4  147000 EX39 5XT         N
```

**Pull request merged**
