### PR TITLE
reformat spacing

### PR DESCRIPTION
**Pull request by mrchypark**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Looks good to me - makes the prose more consistent and tidy.

FYI we're deliberately doing per-sentence line breaks for the [geocompr](https://github.com/Robinlovelace/geocompr) book project in the drafting stage because it makes reading diffs and moving sentences around.

**Comment by mrchypark** [comment]
you means 

This chapter introduces the book. 
It describes the wide range of people it was written for, in terms of R and programming experience, and how you can get the most out of it. 

is prefer than

This chapter introduces the book. It describes the wide range of people it was written for, in terms of R and programming experience, and how you can get the most out of it. 

is that correct?

**Comment by Robinlovelace** [comment]
No I don't mean that - your change looks good.

**Comment by mrchypark** [comment]
I don't understand sentence "we're deliberately doing per-sentence line breaks".

**Comment by Robinlovelace** [comment]
I mean that in a different repo we're using one sentence per line, like this:

```
Sentence one.
Sentence two.
```

But in this repo we're using a style with one paragraph per line, like this:

```
Sentence one. Sentence two. 

Paragraph two.
```

I think your changes adhere to the style used in this repo.

**Comment by mrchypark** [comment]
Oh, understand. Thank you for explain to me.

**Pull request merged**
